src/ByteBank.Forum/Controllers/TopicoController.cs
using ByteBank.Forum.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ByteBank.Forum.Controllers
{
    public class TopicoController : Controller
    {
        [Authorize]
        public ActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Criar(TopicoCriarViewModel modelo)
        {
            return View();
        }
    }
}

src/ByteBank.Forum/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ByteBank Fórum", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Criar novo tópico", "Criar", "Topico")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">

                    @if(Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("Logoff", "Conta", FormMethod.Post, new { id = "formulario_logoff" }))
                        {

                        }

                        <li>
                            <p class="navbar-text">
                                Olá, @Html.ActionLink(User.Identity.GetUserName(), "MinhaConta", "Conta")
                            </p>
                        </li>
                        <li> <a href="javascript:document.getElementById('formulario_logoff').submit()"> Logoff </a> </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Registrar", "Registrar", "Conta")</li>
                        <li>@Html.ActionLink("Login", "Login", "Conta")</li>
                    }
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>